In [5]:
import pandas as pd

In [42]:
safety = pd.read_csv('C:/Users/User/Documents/GitHub/AnotherTown/Data/Cleaned/Safety_Scores.csv', index_col=0)
health = pd.read_csv('C:/Users/User/Documents/GitHub/AnotherTown/Data/Cleaned/Health_Scores.csv', index_col=0)
demo = pd.read_csv('C:/Users/User/Documents/GitHub/AnotherTown/Data/Cleaned/Demo_Scores.csv', index_col=0)

In [43]:
demo[demo['County'].isin(['Los Angeles', 'Elbert'])]

,FIPS,State,County,Population_bins,% 18 to 65,% Non-Hispanic White,Diversity
209,6037,California,Los Angeles,10,10,1,7.00
270,8039,Colorado,Elbert,4,9,7,4.50
449,13105,Georgia,Elbert,3,4,3,5.75

In [62]:
df = demo.copy(deep=True,)
df= df.merge(safety, on=['FIPS', 'State', 'County'])
df= df.merge(health, on=['FIPS', 'State', 'County'])

df['Total'] = df.iloc[:,7:].sum(axis = 1, skipna = True) 
df[df['State'] == 'California'].sort_values(by=['Total'])

,FIPS,State,County,Population_bins,% 18 to 65,% Non-Hispanic White,Diversity,Safety_avg,health_raw,Total
181,6061,California,Placer,8,5,4,6.00,2.372093,1.300000,3.672093
172,6041,California,Marin,7,4,4,6.25,2.720930,1.106667,3.827597
191,6081,California,San Mateo,8,10,1,6.25,2.767442,1.085185,3.852627
193,6085,California,Santa Clara,9,10,1,6.50,2.930233,1.085185,4.015418
180,6059,California,Orange,10,10,1,6.25,3.000000,1.601852,4.601852
205,6111,California,Ventura,9,9,2,6.25,3.372093,2.057037,5.429130
187,6073,California,San Diego,10,10,2,6.75,3.465116,2.040370,5.505487
198,6097,California,Sonoma,8,8,3,6.25,3.697674,1.831852,5.529526
160,6017,California,El Dorado,6,6,5,5.75,3.744186,1.928519,5.672705
206,6113,California,Yolo,7,10,2,6.50,3.488372,2.283148,5.771520
178,6055,California,Napa,6,7,2,6.25,3.953488,1.818519,5.772007
190,6079,California,San Luis Obispo,7,9,3,6.00,3.906977,2.029074,5.936051
185,6069,California,San Benito,5,8,1,6.00,3.139535,2.847778,5.987313
194,6087,California,Santa Cruz,7,10,2,6.00,4.162791,1.907963,6.070754
188,6075,California,San Francisco,9,10,1,6.50,4.767442,1.491852,6.259294
192,6083,California,Santa Barbara,8,9,1,6.25,4.279070,2.059815,6.338885
179,6057,California,Nevada,5,2,6,4.50,4.000000,2.386296,6.386296
153,6001,California,Alameda,9,10,1,6.75,4.837209,1.549444,6.386654
183,6065,California,Riverside,10,8,1,6.75,3.511628,3.119815,6.631443
158,6013,California,Contra Costa,9,9,1,7.00,5.200000,1.466667,6.666667
170,6037,California,Los Angeles,10,10,1,7.00,4.348837,2.451667,6.800504
157,6011,California,Colusa,4,5,1,5.50,3.733333,4.094630,7.827963
154,6005,California,Amador,4,5,5,5.75,5.395349,2.708519,8.103867
164,6025,California,Imperial,6,5,1,6.25,3.302326,4.970000,8.272326
184,6067,California,Sacramento,9,9,1,6.75,5.000000,3.314630,8.314630
197,6095,California,Solano,8,9,1,7.00,5.627907,2.732593,8.360500
186,6071,California,San Bernardino,10,9,1,7.00,4.697674,3.852593,8.550267
199,6099,California,Stanislaus,8,7,1,6.50,4.674419,3.933704,8.608122
200,6101,California,Sutter,5,6,2,6.25,4.209302,4.651852,8.861154
177,6053,California,Monterey,8,7,1,6.50,5.860465,3.032407,8.892873
156,6009,California,Calaveras,4,2,5,4.75,6.023256,3.048333,9.071589
204,6109,California,Tuolumne,5,4,5,5.25,5.666667,3.547778,9.214444
155,6007,California,Butte,7,8,4,6.00,4.860465,4.492963,9.353428
167,6031,California,Kings,6,9,1,6.75,4.558140,5.078148,9.636288
189,6077,California,San Joaquin,8,7,1,6.75,6.046512,3.624074,9.670586
161,6019,California,Fresno,9,6,1,6.75,5.232558,4.620926,9.853484
174,6045,California,Mendocino,5,3,3,5.50,6.255814,4.148704,10.404518
171,6039,California,Madera,6,5,1,6.25,5.488372,4.955741,10.444113
175,6047,California,Merced,7,7,1,6.50,5.534884,5.097222,10.632106
162,6021,California,Glenn,4,4,2,5.50,6.255814,4.390370,10.646184
203,6107,California,Tulare,8,5,1,6.00,5.232558,5.626111,10.858669
182,6063,California,Plumas,3,2,5,4.75,7.533333,3.342037,10.875370
195,6089,California,Shasta,6,4,5,5.25,6.604651,4.482222,11.086873
207,6115,California,Yuba,5,7,2,6.50,6.023256,5.131111,11.154367
201,6103,California,Tehama,5,3,3,5.25,5.930233,5.505741,11.435973
163,6023,California,Humboldt,6,9,4,5.25,7.116279,4.373148,11.489427
169,6035,California,Lassen,4,10,3,6.25,6.767442,4.861852,11.629294
166,6029,California,Kern,9,7,1,6.75,6.534884,5.139259,11.674143
196,6093,California,Siskiyou,4,2,4,5.25,6.627907,5.461111,12.089018
165,6027,California,Inyo,3,3,3,5.25,7.642857,4.861481,12.504339
176,6049,California,Modoc,2,1,5,5.25,7.200000,5.662222,12.862222
173,6043,California,Mariposa,3,3,5,5.00,9.045455,4.092778,13.138232
159,6015,California,Del Norte,4,8,3,6.00,7.953488,5.390556,13.344044
202,6105,California,Trinity,3,2,5,4.25,8.775000,4.777407,13.552407
168,6033,California,Lake,5,3,4,5.50,8.302326,6.035000,14.337326

In [17]:
df[df['County'].isin(['San Diego', 'Los Angeles', 'Ventura', 'Multnomah', 'Teton', 'St. Louis'])]

,FIPS,State,County,Safety_avg,Binned,Diversity,White Pop,age: 18-35,Health_avg,Total
170,6037,California,Los Angeles,4.348837,8,6.50,2,8,5.685926,34.534763
187,6073,California,San Diego,3.465116,2,4.50,3,4,3.850612,20.815729
205,6111,California,Ventura,3.372093,7,6.25,1,5,4.955741,27.577834
474,16081,Idaho,Teton,3.636364,5,5.50,4,8,4.692407,30.828771
1052,27137,Minnesota,St. Louis,4.953488,4,1.50,10,8,7.577778,36.031266
1204,29189,Missouri,St. Louis,7.883721,8,5.75,4,9,2.186667,36.820388
1674,41051,Oregon,Multnomah,5.302326,4,2.00,9,1,4.250556,25.552881

In [11]:
df[df['County'].isin(['Los Angeles'])]

,FIPS,State,County,Safety_avg,Binned,Diversity,White Pop,age: 18-35,Health_avg,Total
170,6037,California,Los Angeles,4.348837,8,6.5,2,8,5.685926,34.534763